# Site settings
title: MTM Systems Official Web Page
email: info@mtmsoftware.jp
description: "株式会社MTMシステムズ"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb

# Postal address (add as many lines as necessary)
address:
  - line: 1-5-1 Chofu-ga-oka Chofu-city Tokyo, 182-8585, Japan
  - line: The University of Electro-Communications
  - line: West Bldg#11, 411

# Build settings
markdown: kramdown
permalink: pretty
